# Generated by Django 5.1.3 on 2024-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tennis_Members', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
